### ISSUE TITLE
Upgrade

### ISSUE THREAD

**Issue by youngef** [odenijs/Menu-Title-Wolf-CMS#1]
There is no tab in the admin for Wolf 0.7.7. Any idea what might be going on?

**Comment by odenijs** [comment]
Hi! I just pushed version 0.2. Updated the plugin to work with Wolf CMS 0.7 and higher. With one of my projects the enable action didn't add the menu_title field to the database. If there's no new field added you have to add it manually using this query:

ALTER TABLE <TABLE_PREFIX>.page ADD menu_title varchar(255) NULL default NULL

Let me know if it works.

**Comment by youngef** [comment]
Still has MISSING_DEFAULT_STRING in the admin, but it works.

**Comment by odenijs** [comment]
Cleaning up old stuff.. this thingy was soooooo long ago :)
